name: qrcoder
description: A simple app to scan, copy, open, create and save QR codes.

publish_to: "none"

version: 1.3.2

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  qr_flutter: ^4.0.0
  image_picker: ^1.0.4
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^10.4.5
  url_launcher: ^6.1.14
  google_mobile_ads: ^3.0.0
  mobile_scanner: ^3.4.1
  qrscan: ^0.3.3

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
