name: qrcoder
description: A simple app to scan, copy, open, create and save QR codes.

publish_to: "none"

version: 1.2.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  qr_flutter: ^4.0.0
  qr_code_scanner: 0.4.0
  qr_code_tools: ^0.0.7
  image_picker: ^0.8.3+3
  screenshot: ^1.2.3
  image_gallery_saver: ^1.6.9
  permission_handler: ^8.1.4+2
  url_launcher: ^6.0.9

flutter:
  uses-material-design: true
